### ISSUE TITLE
Live updates to recently opened files ?

### ISSUE THREAD

**Issue by qorrect** [rakanalh/emacs-dashboard#12]
Possible ?

**Comment by rakanalh** [comment]
What use case would that serve?

**Comment by qorrect** [comment]
I have 'jump-to-dashboard' hotkeyed on my installation , it would be nice to have the recently viewed files list because I go there more than just on startup.

**Comment by rakanalh** [comment]
Ah so what's required is a refresh functionality.

I think this makes sense, are you interesting in contributing this idea?

**Comment by qorrect** [comment]
Sure,  I'll take a stab at it.

**Comment by qorrect** [comment]
Actually closing this , the recent files variable doesn't seem to get updated , and I just found recentf-mode that kind of does all I wanted.

**Comment by rakanalh** [comment]
There's a function called `recentf-load-list` which might trigger rebuilding the list. Did you try that one?

**Comment by qorrect** [comment]
Ok let me try it

**Comment by acowley** [comment]
I'd like this feature, too. @qorrect can you re-open it so there is a place to gather ideas for anyone else who comes along?

**Comment by qorrect** [comment]
Will do.

**Comment by qorrect** [comment]
Hey sorry guys, this is the wrong spot for it I'm sure, but every call I make to any of the (recentf-*) functions returns nill ( just in an emacs-lisp buffer ).  I'm new to elisp.

I notice a (recentf-mode) , in (dashboard-insert-recents ) ... is that call required to use any of the recentf functions ?  Same is true of all elisp code in a mode ?

**Comment by qorrect** [comment]
Okay I've made progress on this sorry, I was missing a call to (recentf-mode) , I guess that call is needed before I call any recentf functions ?

Anyway I can do this one, will check in shortly.

**Comment by acowley** [comment]
I've added this on a [branch](https://github.com/acowley/emacs-dashboard/commit/83aa88d343e115a67d2b49e8de87fc2292acd86c). Do you want to see if it behaves as expected for you, @qorrect? To make it work more nicely for myself, I also advised `recentf` so that switching to a buffer would bump the corresponding file (if there is one) to the top of the recent files list.

To that end, this is in my `use-package recentf` form:

```
(defun recent-buffer (b &rest _)
    (let ((file (buffer-file-name (get-buffer b))))
      (unless (null file) (recentf-add-file file))))
  (advice-add 'switch-to-buffer :after #'recent-buffer)
```

**Comment by qorrect** [comment]
Works for me!

**Comment by rakanalh** [comment]
@acowley cool... can you push a PR with your modifications?

**Comment by rakanalh** [comment]
Merged
