### ISSUE TITLE
Initial startup always asks to create buffer

### ISSUE THREAD

**Issue by mgrbyte** [rakanalh/emacs-dashboard#13]
I've worked around this by pre-creating the `*dashboard*` buffer in my startup definition:
```lisp
(use-package dashboard
  :config
  (get-buffer-create "*dashboard*")
  (dashboard-setup-startup-hook))
```
In the emacs startup sequence, the startup hook is [invoked later][1]  than the init hook, 
so perhaps the order should switch the around?
(i.e switch-to-buffer on startup, do work in init hook?)

[1]: http://emacs.stackexchange.com/questions/14551/whats-the-difference-between-after-init-hook-and-emacs-startup-hook

**Comment by rakanalh** [comment]
Hi @mgrbyte,

Not sure i understand correctly, but do you mean Emacs asks for some input when you launch it?

**Comment by mgrbyte** [comment]
@rakanalh yes, that's correct.
Here's a screen-grab of the behaviour without the `(get-buffer-create "*dashboard*)` line shown above:
![emacs-dashboard-prompt-on-start](https://cloud.githubusercontent.com/assets/3185091/20462624/9ae26ade-af1a-11e6-8ff5-1470862f0e64.png)

I run emacs as a server process, and this prompt prevents it from starting correctly.
The addition of `(get-buffer-create "*dashboard*")` before invoking `(dashboard-setup-startup-hook)` makes it go away.

The problem is that switch to buffer is being [called before][1] the code to [[create the buffer][2],
which is what I was alluding to above in regard to the order of emacs startup hook execution.

[1]: https://github.com/rakanalh/emacs-dashboard/blob/master/dashboard.el#L255
[2]: https://github.com/rakanalh/emacs-dashboard/blob/master/dashboard.el#L247-L253
