### ISSUE TITLE
Shown at startup even when file is passed as argument

### ISSUE THREAD

**Issue by njdan5691** [rakanalh/emacs-dashboard#19]
When I start Emacs with a file as an argument is will open it but the dashboard is still displayed. Would be nice if there was a way to disable or modify this behavior or maybe document it in the README if it cannot be changed. I seen in the wishlist that new banner options are a possibility, would be nice to have one disable the banner.

Thanks for putting this together, very nice work!!!!!

**Comment by qorrect** [comment]
+1 on this.

**Comment by rakanalh** [comment]
Hi @njdan5691,

Yea i'll look into this.

Thanks for adding the issue :)

**Comment by qorrect** [comment]
There is a variable  (command-line-args) , https://www.gnu.org/software/emacs/manual/html_node/elisp/Command_002dLine-Arguments.html .

Still trying to determine how to tell if an item is a file or an argument ( or an option ... )

**Comment by qorrect** [comment]
I think this was fixed in  5910290b40f941271970b1fe6d5da1f0711e958d

**Comment by rakanalh** [comment]
Yup... this is fixed thanks to @qorrect.

**Comment by njdan5691** [comment]
Yup, looks good. Thanks @qorrect.
