### ISSUE TITLE
Duplicate banners, weird clicking behavior

### ISSUE THREAD

**Issue by qorrect** [rakanalh/emacs-dashboard#2]
I have installed it to ~/.emacs.d/dashboard per instructions, and my .emacs file looks like

<code>
(add-to-list 'load-path (concat user-emacs-directory "/dashboard/"))
(require 'dashboard)
(dashboard/setup-startup-hook)
</code>

I do see an error with starting in --debug-init , but it only shows up in the mini buffer, not the *Messages* for some reason:

Symbols definition is void : projectile-mode

**Comment by qorrect** [comment]
Doh, installing projectile-mode fixed it, and everythings clickable!

I still get weird ^L text in my *dashboard* though, 
![2016-11-04-151814_1920x1080_scrot](https://cloud.githubusercontent.com/assets/711385/20020980/f6972340-a2a1-11e6-8bc6-dcfd016a16fb.png)

**Comment by rakanalh** [comment]
Thank you for reporting. You reminded me that i forgot the `require`s as i depended on the packages being their in my configs. I also added documentation for dependencies

**Comment by rakanalh** [comment]
Oh, as for the weird ^L thing, installing page-break-lines package should solve your issue
