### ISSUE TITLE
Show posts from reddit.com/r/emacs

### ISSUE THREAD

**Issue by qorrect** [rakanalh/emacs-dashboard#24]
@rakanalh  could you take a look at my master branch at https://github.com/qorrect/emacs-dashboard .  

I've managed to pull down the latests posts and parse out the score, url and title, but I don't know enough lisp to collect all those items into a list and then create a clickable button with insert-button .  Right now it justs inserts text .

**Comment by qorrect** [comment]
If you add ( reddits . 5 ) to your config, it should show up automagically

**Comment by rakanalh** [comment]
Hi @qorrect,

I see that you're using `insert instead of `widget-create`... is there a reason this function did not work for you?

The other thing is that, although this is related to Dashboard, is this the right place for this? i think this is more of an elisp question that you can direct to reddit / stackoverflow?

**Comment by qorrect** [comment]
I"m trying to avoid learning elisp , I'm hoping to just finish this little addition and be done :).

I'll take a look at widget create, thanks.

**Comment by rakanalh** [comment]
Yup that should work for you... take a look at how the widgets do it and follow the same style.

**Comment by qorrect** [comment]
How would I add generators to dashboard-item-generators , in another file I load myself ?

`(add-to-list dashboard-item-generators '(reddit . dashboard-insert-reddits ))`

Is giving me an error, Wrong type argument, symbol-p .

Just trying to do this one thing, then I'm done.

**Comment by rakanalh** [comment]
You have to quite `dashboard-item-generators` in that case.

Example:
```
(defun dashboard-insert-custom ()
  (insert "Custom text"))
(add-to-list 'dashboard-item-generators  '(custom . dashboard-insert-custom))
(add-to-list 'dashboard-items '(custom) t)
```

**Comment by qorrect** [comment]
Thanks!
