### ISSUE TITLE
Getting the "projectile-mode" is required error

### ISSUE THREAD

**Issue by nayefc** [rakanalh/emacs-dashboard#27]
Hello,

I already have `projectile-mode` installed but I keep getting:

```custom-initialize-reset: Projects list depends on ’projectile-mode‘ to be activated```

Dashboard is working fine on one of my machines but not the other (identical OS, Emacs version and dotfiles), but not the other. I need to run `(projectile-mode)` but then Dashboard doesn't refresh and show me the projects either, so it's pointless.

It seems like when I have dashboard installed on this computer, I need to manually activate projectile. However, when Dashboard is deleted, projectile works on startup.

I use `use-package` to activate my modes. Here is how I activate dashboard:

```
(use-package dashboard
  :config
  (dashboard-setup-startup-hook)
  (setq dashboard-items '((projects . 10)
			  (recents  . 10))))

(provide 'init-dashboard)
```

I'd appreciate any help.

Thanks!

**Comment by rakanalh** [comment]
Did you try adding `(require 'projectile)` before calling `dashboard-setup-startup-hook` for dashboard?

**Comment by rakanalh** [comment]
I think requiring projectile should solve this issue. Closing
