### ISSUE TITLE
Added NBA Scores

### ISSUE THREAD

**Issue by qorrect** [rakanalh/emacs-dashboard#30]
I'll get these up on MELPA soon, have 3 plugins I need to share.

https://github.com/qorrect/emacs-dashboard-nba

**Comment by rakanalh** [comment]
Nice, once you get that one done, i would be happy to add a new section in the README file listing dashboard 3rd-party widgets. Let me know once your stuff are on Melpa.

Thanks

**Comment by qorrect** [comment]
COolio!
