### ISSUE TITLE
Customizing generators with packages from Melpa

### ISSUE THREAD

**Issue by qorrect** [rakanalh/emacs-dashboard#32]
Running my package install locally works fine, but when I try to customize my dashboard with

(nbas . 5 ) 

I'm getting Symbol definition is void or nul. 

It's like it doesn't see my additions to dashboard-item-generators , which I do in this file https://github.com/qorrect/emacs-dashboard-nba/blob/master/dashboard-nba-plugin.el 

Do I need to "require" something from my package in order to add custom generators for the dashboard ?

When I manually load the library in my development environment with (load-file ... ) it works fine.

Thoughts ?

**Comment by rakanalh** [comment]
1 thought actually... check this out: https://www.gnu.org/software/emacs/manual/html_node/elisp/Hooks-for-Loading.html
