### ISSUE TITLE
arbitrary info in logo title?

### ISSUE THREAD

**Issue by mclearc** [rakanalh/emacs-dashboard#34]
I'm trying to put some info under the banner/logo. Right now I have startup time displaying like so:

```emacs-lisp 
(setq dashboard-banner-logo-title (message "Emacs initialized in %.2fs" (float-time (time-subtract (current-time) my-start-time))))
```

I'd love to be able to display the time, the version number of emacs, and perhaps a line of arbitrary text. Is there a way to do all this using `dashboard-banner-logo-title` or do you have an alternative means baked-in? Thanks.

**Comment by rakanalh** [comment]
At the moment, `dashboard-banner-logo-title` is only text that you set or the default value. You can pretty much implement that yourself as dashboard doesn't provide this out of the box. However, i can refer you to: [Prolusion](https://github.com/jwintz/prolusion/blob/master/prolusion-core/prolusion-dashboard.el) where this has been implemented in their customized version of dashboard.

**Comment by mclearc** [comment]
Right - thanks. I'll look at Prolusion again.
