### ISSUE TITLE
Weird yank behavior when clicking

### ISSUE THREAD

**Issue by unbildung** [rakanalh/emacs-dashboard#35]
Thanks for the package.

When using `dashboard` I have been experiencing a bug:

1) I launch a new Emacs session
2) I **_click_** on one of my recent files or bookmarks on the dashboard menu
3) As soon as the buffer opens, the most recent item from the kill-ring from my _**last**_ session is yanked to the top of the buffer (about 5 lines down)

Note that selecting the file with the keyboard doesn't result in this behavior.

I am on a Mac. Any idea what my touchpad clicks are doing? Is the Mac system clipboard interacting weirdly with the dashboard buffer selection mechanism?

**Comment by gergelypolonkai** [comment]
The same happens on Linux, using a mouse.

**Comment by rakanalh** [comment]
I've experienced this case when dashboard uses projectile-mode to load projects list. I've pushed a fix, which is more like an ugly hack in version 1.2. Let me know if this doesn't resolve your issue.

Thanks
