### ISSUE TITLE
pictures can not be shown 

### ISSUE THREAD

**Issue by liulangdefeng2222** [rakanalh/emacs-dashboard#44]
Hi, I am using Windows10, Emacs25.2
my init-dashboard.el has displayed 
![1493959606 1](https://cloud.githubusercontent.com/assets/26605381/25733968/2e8f51c8-3113-11e7-9fbb-d69d4da32927.png)
no matter I choose official or logo, there is no picture shown at the beginning. It always displays the text.
![1493959479 1](https://cloud.githubusercontent.com/assets/26605381/25733981/65bc5f9c-3113-11e7-8ff1-62bf2f2c70b3.png)
Could you tell me what is the metter
Thank you very much.

**Comment by rakanalh** [comment]
Hi @liulangdefeng2222,

I am not sure what's going on... but maybe remove the first two lines (require + dashboard-setup-startup-hook) because it seems like you're using `use-package` which is sufficient. Double check the documentation, you can either use require or use-package but not both.

**Comment by liulangdefeng2222** [comment]
I have removed the "use-package"

(require 'dashboard)
(dashboard-setup-startup-hook)
;; Set the title
(setq dashboard-banner-logo-title "Welcome to Emacs Dashboard")
;; Set the banner
(setq dashboard-startup-banner 'official)
(setq dashboard-items '((recents  . 20)
                        (bookmarks . 5)
                        ;;(projects . 5)
                        (agenda . 5)))

However, it still does not work.

**Comment by rakanalh** [comment]
Ok here's the list of steps you need to do:
1. Figure out which version of dashboard you've installed
2. Try to `ls ~/.emacs/elpa/dashboard-xxx/banners`, do the images exist there?
3. Try to move `(setq` block before the call to `(dashboard-setup-startup-hook)`

**Comment by liulangdefeng2222** [comment]
Thank you very much for your quick reply.
1. I think this should be the newest version (dashboard-20170419.2358)
2. I checked the file, the two images exit here
![1494259591 1](https://cloud.githubusercontent.com/assets/26605381/25813247/abbb6404-33cd-11e7-8e2a-aa1d99220ba9.png)
3. I have moved the (dashboard-setup-startup-hook) down.
![default](https://cloud.githubusercontent.com/assets/26605381/25813390/31a047f6-33ce-11e7-8128-b0be5193c47b.png)
It seems that it still does not work.
![1494259885 1](https://cloud.githubusercontent.com/assets/26605381/25813415/5669f4ce-33ce-11e7-8156-3faeb28f592f.png)

**Comment by adamjustdrewit** [comment]
Hi, I also have this issue. I've also tried using a path to an image using 
`(setq dashboard-startup-banner "~/emacslogo.jpg") `
and without the root
(setq dashboard-startup-banner "C:/[...]/emacslogo.jpg")

Both of these get the same result as above. However, changing between the ascii logos works, so I **can** get a different logo by using:

`(setq dashboard-startup-banner 2)`

Is there a dependency on another lib or program for images to work within emacs? I would guess not as the image on the default emacs splashscreen works, though that could be rendering using a different method.

I'm also on windows if that's any help.

**Comment by adamjustdrewit** [comment]
I've managed to get it working. Out of the box emacs doesn't support images. [Check this stackoverflow question for details on how to get images working in emacs on windows](http://stackoverflow.com/questions/2650041/emacs-under-windows-and-png-files)

Now that I have full image support (as the answer in the link states you can check what image formats are supported by evaluating `(image-type-available-p 'png)`) I can see the image with `(setq dashboard-startup-banner 'logo)`.

This also makes setting a custom image possible with `(setq dashboard-startup-banner "~/gnu.png"):`

![image](https://cloud.githubusercontent.com/assets/28392952/26168948/e980e2d8-3b33-11e7-8744-e7ae77c418d2.png)

Thanks for a great package!

**Comment by rakanalh** [comment]
Hi @adamjustdrewit,

I thought this might be a reason but i didn't get the chance to look into it. Thanks for taking the time. @liulangdefeng2222 can you check if your version supports displaying images or not?

**Comment by liulangdefeng2222** [comment]
Thank you so much @rakanalh and @adamjustdrewit . I have made it.  I have tried @adamjustdrewit 's advises. It may have some not wrong for my vesion. I finally found that it might be the dll promblem.
Here are some advises if someone has the same problems.
1. You have checked that  `(image-type-available-p 'png)`
2.  `(cdr (assq 'png dynamic-library-alist))` find what kind dll you need. If you have put the dll in ~/emacs/bin file, and it still does not work. Than your dll file may be bad.
3. Try to download the vesion suitable for you [here](http://mirrors.ustc.edu.cn/gnu/emacs/windows/). They provide a set of optional dependencies.  ……deps.zip and put it in your files
Hope it help someone.

**Comment by rakanalh** [comment]
Glad the issue is resolved. Enjoy!
