### ISSUE TITLE
banner.txt not present after install

### ISSUE THREAD

**Issue by Glutexo** [rakanalh/emacs-dashboard#46]
My Emacs 25.1.1 complains about missing _banner.txt_ after installing _dashboard_ and defining a startup hook using _use-package_.

> dashboard-insert-ascii-banner-centered: Opening input file: No such file or directory, /Users/Glutexo/.emacs.d/elpa/dashboard-1.0.3/banner.txt

**Comment by rakanalh** [comment]
Hi @Glutexo 

Dashboard does not provide a `banner.txt`. Can you show the code you added to your init.el to start using dashboard?

**Comment by Glutexo** [comment]
Thanks for response! I used the snipped from README:

```elisp
(use-package dashboard
  :config
  (dashboard-setup-startup-hook))
```

Putting a _banner.txt_ file in the location mentioned solved the problem. I was just not expecting this would prevent _dashboard_ from running. It doesn’t feel right to me, however, to directly put a file into the package directory.

**Comment by rakanalh** [comment]
I agree... the weird thing is, the default will try to load an image banner rather than a txt file.

**Comment by Glutexo** [comment]
Well, may I somehow assist you with debugging?

Just to add more info, I am using Emacs 25.1 (9.0) on macOS 10.12.4. I’m not aware of any unusual configuration.

**Comment by terrymunro** [comment]
Hey I'm also seeing this issue.

I've noticed inside of `~/.emacs.d/elpa/dashboard-1.0.3/` the banners directory isn't being installed.
It only contains:
`dashboard-autoloads.el  dashboard.el  dashboard.elc  dashboard-pkg.el`

Is that right?

**Comment by rakanalh** [comment]
@terrymunro i downloaded the latest version on melpa:
https://melpa.org/#/dashboard
and banners folder is there. Are you installing from melpa stable?

**Comment by rakanalh** [comment]
After double checking, i think the answer is yes. I'll upload an updated version tonight.

**Comment by terrymunro** [comment]
@rakanalh Yes you're right. I had melpa-stable set at a higher priority.

Thank you :+1:

**Comment by rakanalh** [comment]
https://github.com/rakanalh/emacs-dashboard/releases/tag/1.2.3
Melpa stable should have the code in a few hours.

**Comment by Hkyx** [comment]
Hi @rakanalh ,

Go the same issue on emacs 26.3 
cfg : 
``` 
(setq initial-buffer-choice (lambda () (get-buffer "*dashboard*")))
(require 'dashboard)
(dashboard-setup-startup-hook)
;; Or if you use use-package
(use-package dashboard
  :ensure t
  :config
  (dashboard-setup-startup-hook))

```
got the no such file or directory error when start my emacs
