### ISSUE TITLE
Open the dashboard when it's closed

### ISSUE THREAD

**Issue by nico202** [rakanalh/emacs-dashboard#54]
Hi, if I kill the *dashboard* buffer, how do I open it again?

Thanks, Nicolò

**Comment by rakanalh** [comment]
you can call `M-x dashboard-insert-startupify-lists`. I should probably give it a better name.

**Comment by nico202** [comment]
Thanks, it works but is not intuitive XD maybe provide something like this (not an elisp dev)

```
(defun dashboard ()
  (interactive)
  (let ((buffer "*dashboard*"))
    (when (not (get-buffer buffer))
      (dashboard-insert-startupify-lists))
    (switch-to-buffer buffer)))
```
