### ISSUE TITLE
projectile widget: customizable switch function

### ISSUE THREAD

**Issue by tomterl** [rakanalh/emacs-dashboard#56]
The projectile widget uses `projectile-switch-project-by-name` hardcoded. I use projectile in conjunction with perspective.el. Currently I have an `:override` in place for `dashboard-insert-project-list`, that calls `projectile-persp-switch-project` instead of `projectile-switch-project-by-name`.

Would you consider adding a `defcustom` to make this function configurable, or to accept a PR to that effect?

Something like:
```elisp
(defcustom dashboard-projectile-switch-f
 #'projectile-switch-project-by-name
  "Functions that will be used to switch to projects."
  :type '(set :value-type function)
:group 'dashboard)
```

**Comment by rakanalh** [comment]
Hi @tomterl 

I think the easier alternative for you is to override `dashboard-item-generators` to register you overridding function:
https://github.com/rakanalh/emacs-dashboard/blob/master/dashboard-widgets.el#L54
This is also mentioned here:
https://github.com/rakanalh/emacs-dashboard/blob/master/README.org#configuration at the end.

Would that be any helpful to your use case?

Regarding perspective.el, i've been thinking about introducing this for quite a while now... that would be an awesome addition to emacs-dashboard if you're interested in contributing.

Thanks

**Comment by tomterl** [comment]
Hi,

many thanks for your prompt reply (and the dashboard in the first place!).
Changing `dashboard-item-generators` instead of my overriding advice
 wouldn't change the underlieing problem,that I don't want to copy your projectile code just to change the project-switching function. Maybe the correct approach would be to adapt projectile.el itself to change it's behaviour if one indicates that each project should have its own perspective...

As to perspectve.el integration: What do you have in mind? Contributing to or writing a generator should be not to hard for me.

kind regards,
Tom
