### ISSUE TITLE
Does we have a way to put GIF image on logo?

### ISSUE THREAD

**Issue by adakbar** [rakanalh/emacs-dashboard#62]
I'm kinda curious, does we have a way to put GIF image on logo? maybe using `imagemagick` just like `image-mode`?

**Comment by rakanalh** [comment]
Hello @adakbar,

I am not really sure as i haven't tried doing this. did you try the following configurations with a gif image?
```
(setq dashboard-startup-banner "path/to/your/image.png")
```

**Comment by jrfferreira** [comment]
@rakanalh with the suggested setting, the image is rendered without the animation.

**Comment by rakanalh** [comment]
Hi @jrfferreira ... am not sure if emacs supports rendering and animating all the frames that exist in a gif. That being said, i think this is more Emacs-centric than a Dashboard one. 
I'll go ahead and close this issue.
