### ISSUE TITLE
Dashboard not seen in emacs25

### ISSUE THREAD

**Issue by maindoor** [rakanalh/emacs-dashboard#63]
Hi,

I have enabled dashboard as per the instructions, but I see only the scratch
buffer if I restart emacs. I don't see the dashboard. Is there anything obvious
I need to check ?

Thanks.

**Comment by maindoor** [comment]
I'll close this issue. I was using a startup file with a few arguments for starting emacs. When I removed it all I got the dashboard.

**Comment by olymk2** [comment]
Just hit this myself just call the below before initial buffer choice.

    (dashboard-insert-startupify-lists)

This will create the buffer and populate it so its available to switch to.
