### ISSUE TITLE
Something strange with my org mode

### ISSUE THREAD

**Issue by smartepsh** [rakanalh/emacs-dashboard#78]
There is some something strange for my org agenda. If I have set `org-agenda-files` to not nil, my spaceline could not work in org-mode. 

emacs version: 26.1
system: osx darwin

If open org file through `*dashboard*` buffer, the mode line looks like this:
![image](https://user-images.githubusercontent.com/3273295/44803678-b790fa80-abf1-11e8-99d8-bd685603d20f.png)

But if open file with `find-file`, the mode line looks normal.
![image](https://user-images.githubusercontent.com/3273295/44804124-09865000-abf3-11e8-8559-3955701eebe0.png)

I'm don't know why (emacs noob...), please help.

**Comment by rakanalh** [comment]
Hi @smartepsh,

I am not sure this is even related to Dashboard as it doesn't tamper with any modeline related functionality.

**Comment by smartepsh** [comment]
Thanks for reply @rakanalh , 
But If I don't run `(dashboard-setup-startup-hook)` function, It's all ok. That's why I submit this issue here for help. 

If you need any other information, I will provide. Thanks.

**Comment by imalightbulb** [comment]
How did you solve this @smartepsh ?
I am facing a similar error too, when I use the `(dashboard-setup-startup-hook)`, org mode is not working and I need to activate it myself. 
When I use find-file, org mode activates by default.
