### ISSUE TITLE
Allow startup list customization

### ISSUE THREAD

**Issue by wynro** [rakanalh/emacs-dashboard#8]
As commented by purcell in melpa/melpa#4393, the startup list is harcoded.

How about giving the user 2 lists, one of pairs `(:symbol . 'function)`, and another of `:symbols`, the first list defines the relationship between symbols (options) and the functions that will create them. The second will define the ordering of the elements. That way each user can define their own personal options easily.

**Comment by andjscott** [comment]
I haven't programmed with elisp so but how does this look? https://github.com/andjscott/emacs-dashboard/blob/customizable/dashboard.el#L224

**Comment by rakanalh** [comment]
Hello @andjscott,

Could you please open an PR? It's easier to discuss changes in the PR page.

**Comment by rakanalh** [comment]
merged into master
